name: Lint Code Base

on:
  push:
    branches: main
    paths: 
      - '**.json'
      - '.github/workflows/linter.yml'
  pull_request:
    paths:
      - '**.json'
      - '.github/workflows/linter.yml'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GLOBAL_PATH }}
